from sklearn.linear_model import SGDClassifier


class CorrectnessModel:
	
	def __init__(self,classifier=SGDClassifier(loss='log',penalty='l2',shuffle=True)):
		self.clf = classifier

	def fit(self,features,labels):
		self.clf.fit(features,labels)

	def predict(self,X,pos):
		"""
		This is kind of tricky one. In the training process, the classifier
		recerives the position values. But in the test process they are not
		given in test sample. Instead, the classifier takes pos argument generated by Position
		Model as input and combine it to the other features.
		"""
		return self.clf.predict(list(X)+[pos])

if __name__ == "__main__":
	X = [[1,3,4,30],
		 [3,4,1,25],
		 [2,2,5,35],
		 [6,1,2,80],
		 [4,6,2,75],
		 [5,3,8,68]]

	Y = [0,0,0,1,1,1]

	correctness = CorrectnessModel()
	correctness.fit(X,Y)

	test = [4,3,3]

	print correctness.predict(test,40)


